#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const repoRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const outputPath = path.join(repoRoot, "docs", "shared", "auth-runtime.js");

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }
  const text = fs.readFileSync(filePath, "utf8");
  const env = {};
  for (const rawLine of text.split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }
    const eq = line.indexOf("=");
    if (eq <= 0) {
      continue;
    }
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1).trim().replace(/^"(.*)"$/, "$1");
    env[key] = value;
  }
  return env;
}

function buildRuntimeConfig() {
  const envFromDotEnv = parseEnvFile(path.join(repoRoot, ".env"));
  const envFromLocal = parseEnvFile(path.join(repoRoot, ".env.local"));
  const env = { ...envFromDotEnv, ...envFromLocal, ...process.env };

  const firebase = {
    apiKey: env.VITE_FIREBASE_API_KEY || "",
    authDomain: env.VITE_FIREBASE_AUTH_DOMAIN || "",
    projectId: env.VITE_FIREBASE_PROJECT_ID || "",
    appId: env.VITE_FIREBASE_APP_ID || "",
    storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET || "",
    messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID || "",
    measurementId: env.VITE_FIREBASE_MEASUREMENT_ID || "",
  };

  const requiredKeys = ["apiKey", "authDomain", "projectId", "appId"];
  const hasRequired = requiredKeys.every((key) => Boolean(firebase[key]));

  return {
    bypassAuth: String(env.VITE_AUTH_BYPASS || "").toLowerCase() === "true",
    firebase: hasRequired ? firebase : null,
  };
}

function generateScript(config) {
  return `// AUTO-GENERATED BY scripts/generate_docs_auth_runtime.mjs. DO NOT EDIT.
window.__CARD_AUTH_RUNTIME__ = ${JSON.stringify(config, null, 2)};
`;
}

const runtimeConfig = buildRuntimeConfig();
fs.writeFileSync(outputPath, generateScript(runtimeConfig));
console.log(`Generated docs/shared/auth-runtime.js (${runtimeConfig.firebase ? "firebase config present" : "firebase config missing"})`);
